[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "3.9.1"
proconio = { version = "0.4.5", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
